version: "3.7"

networks: 
  mynetwork:
    name: mynetwork
    attachable: true    

services:
  
  postgres:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      networks:
       - mynetwork
       
  redis:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    image: redis
    ports:
      - "6379:6379"
    networks:
       - mynetwork       

        
  keycloak:
    image: jboss/keycloak:13.0.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 3333:8080
    depends_on:
      - postgres
    networks:
      - mynetwork


  nginx:
    image: sobolmisha/fresh-ngnix
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  
    networks:
      - mynetwork
    volumes: 
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro

  web:
    image: papiserver
    restart: always
    networks:
      - mynetwork

volumes:
  postgres_data:         